site_name: Apple Silicon MC 光影指南
theme:
  name: material
  logo: ./imgs/icon.png
  favicon: ./imgs/icon.png
  palette:
        primary: "green"
        accent: "green"
  language: zh
  font:
      text: Noto Sans  # 常规字体
      code: Jetbrains Mono  #代码块字体
  features:  #导航
    - navigation.instant  #即时加载
    - navigation.tracking  #锚点跟踪
    - navigation.sections  #次级目录在侧边栏中呈现为组，与tabs同存则有2级导航
    - navigation.expand  #左侧边栏全展开，取消则折叠其他只展开当选
    - navigation.top  #返回顶端
    - search.suggest  #搜索建议，省略回车
    - search.highlight  #搜索词高亮突出显示
    - header.autohide  #标题自动隐藏

markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/WhatDamon/AppleSilicon-MCShaders
copyright: 本网站使用 CC0 许可证供所有人免费查阅, 其中部分资源原作者版权所有<br />由 WhatDamon 管理
site_description: "致力于成为 Apple Silicon 用户提供一站式光影支持查阅服务"

nav:
  - "index.md"
  - "contribute.md"
  - "M4 系列":
    - "Mac16,1": "Mac16,1.md"

extra:
  generator: false 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WhatDamon
      name: GitHub
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/351191993
      name: 哔哩哔哩

extra_javascript:
  - js/detect-os.js