name: 提交数据
description: 在这里提交您的测试数据!
title: "[UPLOAD]: "
labels: ["upload"]
body:
  - type: markdown
    attributes:
      value: |
        欢迎提交您的测试数据
        请仔细完成本 Issue 模板的全部要求内容, 任何不符合要求的 Issue 将不会受理并 **Closed as not planned**.
  - type: checkboxes
    id: noduplicate
    attributes:
      label: 重复 Issue 检查
      description: 为了提高效率，请搜索 Issues 看看您要找的模组是否已经有人请求过了.
      options:
        - label: 我确定没有一个 issue 与我所提交的内容是重复的!
          required: true
  - type: input
    id: model
    attributes:
      label: 设备标识符
      description: 您可以在 https://damon233.top/AppleSilicon-MCShaders/contribute/#__tabbed_1_2 中查看如何获取设备标识符.
      placeholder: 例如 Mac16,1
    validations:
      required: true
  - type: input
    id: shadername
    attributes:
      label: 光影名称
      description: 请提供光影的名称.
      placeholder: Complementary Shaders - Reimagined
    validations:
      required: true
  - type: input
    id: shaderversion
    attributes:
      label: 光影版本
      description: 请提供光影的版本.
      placeholder: r5.5.1
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: 运行状态
      multiple: false
      options:
        - ✅ (可能) 正常运行
        - 🟠 报错，但运行了，或者运行后存在明显异常
        - ❌ 不能运行
    validations:
      required: true
  - type: textarea
    id: error_key
    attributes:
      label: 错误关键
      description: 如果存在错误, 请提供错误关键信息, 详见 https://damon233.top/AppleSilicon-MCShaders/contribute/#_6 .
    validations:
      required: false
  - type: textarea
    id: proof
    attributes:
      label: 证明
      description: 请参考 ttps://damon233.top/AppleSilicon-MCShaders/contribute#_9 .
      placeholder: 直接把图片拖拽进来即可
    validations:
      required: true
  - type: checkboxes
    id: trust
    attributes:
      label: 保证
      description: 请同意以下内容以继续.
      options:
        - label: 我保证此 PR 没有任何作假, 并愿意将我的测试数据以 CC0 许可证置于公共领域
          required: true